package:
  name: plastinet
  version: "v0.1.4"

source:
  url: https://github.com/izabellaleahz/plastinet/archive/refs/tags/v0.1.4.tar.gz
  sha256: 1f7c9d57f5cb40e0c1673aa46ab20fd42fad1543004bdc9ccbe4c3f7e487afa4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python=3.10
    - pip
  host:
    - python=3.10
    - pip
  run:
    - python=3.10
    - numpy
    - pandas
    - scikit-learn
    - torchvision
    - matplotlib
    - anndata
    - squidpy
    - scanpy
    - cmcrameri
    - pip
    - pygam
    - ipykernel
    - pyg
  channels:
    - pyg
    - conda-forge
test:
  imports:
    - plastinet
    - pyg

about:
  home: https://github.com/izabellaleahz/plastinet
  license: MIT
  summary: "Plastinet is Python package for spatial transcriptomics."
  description: "PlastiNet is a graph attention-based network (GAT) designed to analyze spatial transcriptomics data and uncover the mechanisms of cellular plasticity in the tumor microenvironment."
  dev_url: https://github.com/izabellaleahz/plastinet/issues

extra:
  recipe-maintainers:
    - izabellaleahz
    - zhang-lucy
